### ISSUE TITLE
Is there any way to test that our integration works correctly?

### ISSUE THREAD

**Issue by ashutoshpathak200** [uerceg/play-install-referrer-react-native#4]
Hello, Thanks for this library.
How can we test that we get the correct install referrer after integrating this library?

**Comment by samilCW** [comment]
So I did find a way.
- Generate an url with referral code from [here](https://developers.google.com/analytics/devguides/collection/android/v3/campaigns#google-play-url-builder)
- Open play store on device by directly clicking on that generated link
- While the play store is open, install the debug apk from the command line.
- Now the play store page will show open instead of install since it sees the same package already installed on device
- After the first install, the url should contain all the campaign/referral information

Worked for me

**Comment by uerceg** [comment]
Hi @ashutoshpathak200 

Sorry for delayed reply and big thanks to @samilCW for the description! 🍺 That's pretty much exactly the way how you can test this.

In case you have any issues / questions with flow which @samilCW suggested, feel free to ping!

**Comment by ashutoshpathak200** [comment]
Thanks. This works.
